# GitHub Sponsors configuration for ApertaCodex/ak

# Remove or comment out funding platforms that aren't set up yet
github: moussa-m # Replace with your GitHub username
# patreon: moussamokhtari
# open_collective: moussamokhtari
# ko_fi: moussamokhtari
# liberapay: moussamokhtari

# Custom funding URLs
custom: ["https://buymeacoffee.com/moussa.m"]