# GitHub Sponsors configuration for ApertaCodex/ak

# Remove or comment out funding platforms that aren't set up yet
github: moussa-m # Commented out - not enrolled in GitHub Sponsors yet
# liberapay: moussa.m
# patreon: moussa-m
# open_collective: moussamokhtari
# ko_fi: moussamokhtari
# buy_me_a_coffee: moussa.m
