# GitHub Sponsors configuration for ApertaCodex/ak

# Remove or comment out funding platforms that aren't set up yet
# github: apertacodx
# patreon: apertacodx
# open_collective: apertacodx
# ko_fi: apertacodx
# liberapay: apertacodx

# Custom funding URLs (when ready)
# custom: ["https://apertacodx.com/sponsor", "https://paypal.me/apertacodx"]