name: Update Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 3.4.0)'
        required: true
        type: string

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
            VERSION=${VERSION#v}  # Remove 'v' prefix if present
          else
            VERSION="${{ github.event.inputs.version }}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Generate Homebrew formula
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          RELEASE_URL="https://github.com/apertacodex/ak/archive/v${VERSION}.tar.gz"
          
          # Calculate SHA256 checksum
          echo "Calculating SHA256 for $RELEASE_URL"
          SHA256=$(curl -fsSL "$RELEASE_URL" | sha256sum | cut -d' ' -f1)
          echo "SHA256: $SHA256"
          
          # Generate the formula
          ./macos/homebrew/scripts/generate-formula.sh \
            --version "$VERSION" \
            --url "$RELEASE_URL" \
            --sha256 "$SHA256" \
            --owner "apertacodex" \
            --repo "ak"
          
          # Copy to main Formula directory
          cp macos/homebrew/generated/ak.rb Formula/ak.rb
          
          echo "✅ Updated Formula/ak.rb for version $VERSION"

      - name: Validate formula
        run: |
          # Check if Homebrew is available
          if command -v brew >/dev/null 2>&1; then
            brew audit --strict Formula/ak.rb || echo "Audit warnings (non-blocking)"
            brew style Formula/ak.rb || echo "Style warnings (non-blocking)"
          else
            echo "Homebrew not available, skipping validation"
          fi

      - name: Commit and push formula update
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if there are changes
          if ! git diff --quiet Formula/ak.rb; then
            git add Formula/ak.rb
            git commit -m "Update Homebrew formula to version $VERSION"
            git push
            echo "✅ Formula update committed and pushed"
          else
            echo "No changes to Formula/ak.rb"
          fi

      - name: Create summary
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          cat >> $GITHUB_STEP_SUMMARY << EOF
          # Homebrew Formula Updated

          ## Version: $VERSION

          ### Installation Commands
          \`\`\`bash
          brew tap apertacodex/ak https://github.com/apertacodex/ak.git
          brew install ak
          \`\`\`

          ### Verification
          \`\`\`bash
          ak --version  # Should show: ak version $VERSION
          \`\`\`

          The Formula/ak.rb has been updated with the new version and SHA256 checksum.
          EOF